# ===============================
# Application
# ===============================
app.name=HomeRent
app.version=1.0.0
app.description=Home rental service system
app.contact.email=support@homerent.com
app.contact.url=https://homerent.example.com
spring.profiles.active=dev
# ===============================
# Server
# ===============================
server.port=8080
# ===============================
# H2 Database (DEV)
# ===============================
spring.datasource.url=jdbc:h2:mem:homerent_dev;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# H2 console (for development purposes)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false
# ===============================
# JPA / Hibernate
# ===============================
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
# ===============================
# Liquibase
# ===============================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# ===============================
# Mail (DEV)
# ===============================
app.mail.from=${EMAIL_FROM_USERNAME}
app.public.base-url=http://localhost:8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_FROM_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ===============================
# Multipart upload
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
app.upload.rental-contracts-dir=./uploads/rental-contracts
app.upload.rental-contracts-max-size=15728640
app.upload.properties-dir=./uploads/properties
app.upload.property-max-size=5242880

